{
 "title": "Fan-out",
 "time": { "from": "2024-12-12T17:30:39.099Z", "to": "2024-12-12T17:36:30.205Z" },
 "templating": {
  "list": [
   { "name": "Applications", "query": "label_values(application)" },
   {
    "name": "Servers",
    "query": "label_values(akka_stream_stream_running_streams{application=~\"$Applications\"}, host)"
   },
   {
    "name": "ActorSystems",
    "query": "label_values(akka_stream_stream_running_streams{host=~\"$Servers\", application=~\"$Applications\"}, actor_system)"
   },
   {
    "name": "Streams",
    "query": "label_values(akka_stream_stream_running_streams{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\"}, stream)"
   },
   {
    "name": "Operators",
    "query": "label_values(akka_stream_operator_running_operators{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\"}, operator)"
   },
   {
    "name": "Quantile",
    "query": "label_values(akka_stream_operator_processing_time_ns, quantile)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_stream_stream_running_streams{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\"}",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}}"
    }
   ]
  },
  {
   "title": "Running operators per stream",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_stream_stream_running_operators{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\"}",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}}"
    }
   ]
  },
  {
   "title": "Stream throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops", "label": "elements/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_stream_stream_throughput{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\"}[1m])",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}}"
    }
   ]
  },
  {
   "title": "Operator failure rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops", "label": "failures/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_stream_operator_operator_failure{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\", operator=~\"$Operators\"}[1m])",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}} / {{operator}}"
    }
   ]
  },
  {
   "title": "Operator throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops", "label": "elements/second" }
   ],
   "targets": [
    {
     "expr": "irate(akka_stream_operator_throughput{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\", operator=~\"$Operators\"}[1m])",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}} / {{operator}}"
    }
   ]
  },
  {
   "title": "Operator processing time ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "akka_stream_operator_processing_time_ns{host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\", operator=~\"$Operators\", quantile=~\"$Quantile\"}",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}} / {{operator}}"
    }
   ]
  },
  {
   "title": "Branch 0 processing time ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(\n  akka_stream_operator_processing_time_ns{\n    host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\", quantile=~\"$Quantile\",\n    operator=~\"0-1-bigGraph-iterableSource-mysource|0-3-bigGraph-flow0-identityOp|0-4-bigGraph-foreachSink-sink0-ignoreSink|0-5-bigGraph-foreachSink-sink0-map\"\n  }\n)\n",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}} "
    }
   ]
  },
  {
   "title": "Branch 1 processing time ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(\n  akka_stream_operator_processing_time_ns{\n    host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\", quantile=~\"$Quantile\",\n    operator=~\"0-1-bigGraph-iterableSource-mysource|0-7-bigGraph-flow1-identityOp|0-8-bigGraph-foreachSink-sink1-ignoreSink|0-9-bigGraph-foreachSink-sink1-map\"\n  }\n)\n",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}} "
    }
   ]
  },
  {
   "title": "Branch 2 processing time ($Quantile quantile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(\n  akka_stream_operator_processing_time_ns{\n    host=~\"$Servers\", application=~\"$Applications\", actor_system=~\"$ActorSystems\", stream=~\"$Streams\", quantile=~\"$Quantile\",\n    operator=~\"0-1-bigGraph-iterableSource-mysource|0-11-bigGraph-flow2-identityOp|0-12-bigGraph-foreachSink-sink2-ignoreSink|0-13-bigGraph-foreachSink-sink2-map\"\n  }\n)\n",
     "legendFormat": "{{application}} / {{actor_system}} / {{stream}} "
    }
   ]
  }
 ]
}